export const BookActions = {
    LOAD_BOOKS: 'LOAD_BOOKS',
    ON_BOOKS_RECEIVED: 'ON_BOOKS_RECEIVED',
    GET_BOOK_DETAILS: 'GET_BOOK_DETAILS',
    ON_BOOK_DETAILS_RECEIVED: 'ON_BOOK_DETAILS_RECEIVED',
    ADD_TO_CART: 'ADD_TO_CART',
    PLACE_ORDER: 'PLACE_ORDER',
    START_FETCHING: 'START_FETCHING'
}

export const CartActions = {
    ADD_TO_CART: 'ADD_TO_CART',
    PLACE_ORDER: 'PLACE_ORDER',
    ON_ORDER_PLACED: 'ON_ORDER_PLACED'
}
